---
title: "TUBES 2"
author: "Naufal Aziz Ferdian, Favian Arkanda, Azzelya Thiarnady"
date: "2025-11-17"
output: html_document
---

## 0. Persiapan Library

```{r}
library(tidyverse)
library(car)
library(ggpubr)
library(DescTools)
library(rstatix)
library(readr)  
library(dplyr)
```

## 1. Import Data

```{r}
df <- read.csv("Dataset Tugas Besar ADS 2025 - Karakteristik Mahasiswa .csv")
```

## 2 .Data cleaning 

```{r}
str(df)
colSums(is.na(df))
```

```{r}
df$IPK.raw <- df$IPK.Terakhir

# 1. Mengubah koma menajadi titik
df$IPK.clean <- gsub(",", ".", df$IPK.raw)

# 2. Ubah teks non_numerik ("-", "Belum ada", dll) menjadi NA 
df$IPK.clean[df$IPK.clean %in% c("-", "Belum ada", "belum diketahui", "", " ", NA )] <- NA

# 4. Konversi ke numeric
df$IPK.clean <- as.numeric(df$IPK.clean)

# 5. Cek Hasil
summary(df$IPK.clean)
```

```{r}
df$Tinggi.clean <- df$Tinggi.Badan..|>
  tolower()|>
  gsub("cm", "", x = _)|>
  gsub("[a-z]", "", x = _)|>
  parse_number()

df$Berat.clean <- df$Berat.Badan..|>
  tolower()|>
  gsub("kg", "", x = _)|>
  gsub("[a-z]", "", x = _)|>
  parse_number()



df %>% filter(Tinggi.clean < 130  | Tinggi.clean > 210 )
df$Tinggi.clean[df$Tinggi.clean < 130] <- NA

# Konversi Tinggi ke meter 
df$Tinggi.m <- df$Tinggi.clean / 100

# Hitung BMI
df$BMI <- df$Berat.clean / (df$Tinggi.m^2)
  
summary(df[, c("Tinggi.Badan..", "Tinggi.clean", "Berat.Badan..", "Berat.clean", "BMI")])

df$BMI_cat <- cut(df$BMI, breaks=c(-Inf,18.5,25,30,Inf),
                  labels=c("Under","Normal","Over","Obese"))
```

## 3 .EDA

```{r}
library(ggplot2)
ggplot(df, aes(BMI, IPK.clean)) +
  geom_point(alpha=10) +
  geom_smooth(method="loess") +
  facet_wrap(~ BMI_cat)
```

## 4 .ANOVA

```{r}
# Model Bivariat 
# IPK ~ kerelibatan

model <-aov(df$IPK.clean ~ df$Keterlibatan.Organisai)
summary(model)

# IPK ~ BMI
model <-aov(df$IPK.clean ~ df$BMI)
summary(model)

# IPK ~ keterlibatan + BMI
model <- aov(df$IPK.clean ~ df$BMI + df$Keterlibatan.Organisai)
summary(model)

```
